### ISSUE TITLE
Ignoring non-standard tags

### ISSUE THREAD

**Issue by ysilvestrov** [ms5991/BeerXMLSharp#18]
According to http://www.beerxml.com/beerxml.htm

> Non-Standard Tags
> Per the XML standard, all non-standard tags will be ignored by the importing program.  This allows programs to store additional information if desired using their own tags.  Any tags not defined as part of this standard may safely be ignored by the importing program.

however, when I try to deserialize the following XML (which is actually a part of saved beersmith recipe)
```
<?xml version="1.0" encoding="utf-8" ?>
<Recipes>
  <_MOD_>1969-12-31</_MOD_>
  <Name>Recipes</Name>
</Recipes>
```
i'm getting the exception
```
BeerXMLSharp.BeerXMLUnknownTypeTagException : Tag with name [Name] has no corresponding IBeerXMLEntity type!
   at BeerXMLSharp.Serialization.XDocumentBeerXMLSerializer.GetEntityFromElement(XElement element)
   at BeerXMLSharp.Serialization.XDocumentBeerXMLSerializer.GetEntityFromElement(XElement element)
   at BeerXMLSharp.Serialization.XDocumentBeerXMLSerializer.Deserialize(Stream stream)
   at BeerXMLSharp.BeerXML.Deserialize(Stream stream)
```

Please let me know if there is an intended way to get rid of it.

**Comment by ms5991** [comment]
Hi - thanks for the issue. Thanks for pointing out the bug, I've fixed it in [this PR](https://github.com/ms5991/BeerXMLSharp/pull/19).

I added the ability to toggle the exception behavior using BeerXML.StrictModeEnabled. The default value is false, meaning this exception will not be thrown. You can set it to true to reenable the exception. I thought it would be good to have that ability in case you want to valid input or know whether there was an invalid tag.

You should be able to see the bug fix in version 1.1.1 on nuget, which is now live.

Please feel free to leave more issues or contribute. Thanks!
